<?php

namespace ApiBundle\Repository;

use ApiBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function save(User $user)
    {
        try {
            if (empty($user)) {
                throw  new \RuntimeException('Empty User');
            }

            $currentDate = new \DateTime('now', new \DateTimeZone("America/Sao_Paulo"));
            if (empty($user->getCreatedAt())) {
                $user->setCreatedAt($currentDate);
            }
            $user->setUpdatedAt($currentDate);

            $manager = $this->getEntityManager();
            $manager->persist($user);
            $manager->flush();
        }
        catch (\Exception $e) {
            throw  new \RuntimeException($e->getMessage());
        }
    }
}
